name: tubez
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^2.0.0
  font_awesome_flutter: ^10.4.0
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.6
  google_nav_bar: ^5.0.6
  get: ^4.6.6
  speech_to_text: ^7.0.0
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.0.15
  intl: ^0.18.0
  pdf: ^3.11.1
  printing: ^5.13.4
  http_parser: ^4.0.2
  http: ^0.13.6
  mime: ^2.0.0
  path: ^1.9.0
  fluttertoast: ^8.2.8
  rflutter_alert: ^2.0.7
  awesome_snackbar_content: ^0.1.1
  barcode: ^2.1.0
  
dev_dependencies:
  camera: ^0.10.5+2
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mobile_scanner: ^3.2.0 # scan QR code
  path_provider: ^2.0.15 # provide path to save file
  qr_flutter: ^4.1.0 # generate qr code
  carousel_slider: ^5.0.0
  responsive_sizer: ^3.3.1
  book_my_seat: ^1.0.1
  flutter_svg: ^1.0.0
  image_picker: ^1.1.2
  json_serializable: ^6.9.0
  build_runner: ^2.1.4
  
flutter:
  uses-material-design: true

  assets:
    - assets/storage/films/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-Light.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
